using System.Collections.Generic;

namespace Grimhand.Core
{
    /// <summary>卡牌升级配置（对照 Grimhand实际内容总览表 v0.93 · 卡牌 sheet）。</summary>
    public static class CardUpgradeCatalog
    {
        public sealed class UpgradeSpec
        {
            public int MaxUpgrades { get; set; }
            public int DamagePerLevel { get; set; }
            public int BlockPerLevel { get; set; }
            public int HealPerLevel { get; set; }
            public int CostReductionPerLevel { get; set; }
            public int PoisonStacksPerLevel { get; set; }
            public int SlowStacksPerLevel { get; set; }
            public int DrawPerLevel { get; set; }
            public int DamageReductionPerLevel { get; set; }
            /// <summary>应对减伤百分比（铁壁弹反等 GainBlockFromLastDamagePercent / 誓死守护 Guard 层数）。</summary>
            public int RespondMitigationPerLevel { get; set; }
            /// <summary>反弹伤害百分比（ReflectLastDamageToAttacker）。</summary>
            public int ReflectPercentPerLevel { get; set; }
            /// <summary>增伤百分比层数（attack_up_pct / BuffAllOtherAllies 等）。</summary>
            public int AttackUpPercentPerLevel { get; set; }
            /// <summary>强固/护甲百分比层数（defense_up_pct）。</summary>
            public int DefenseUpPercentPerLevel { get; set; }
            /// <summary>虚弱百分比层数。</summary>
            public int WeakenPerLevel { get; set; }
            /// <summary>破损百分比层数。</summary>
            public int VulnerablePerLevel { get; set; }
            public int XpCostPerLevel { get; set; }
        }

        static readonly Dictionary<string, UpgradeSpec> ByDisplayName = Build();

        public static bool TryGetByDisplayName(string displayName, out UpgradeSpec spec)
        {
            if (string.IsNullOrEmpty(displayName))
            {
                spec = null;
                return false;
            }

            if (ByDisplayName.TryGetValue(displayName, out spec))
                return true;

            if (displayName == "太阳审判" && ByDisplayName.TryGetValue("日光审判", out spec))
                return true;

            spec = null;
            return false;
        }

        public static bool CanUpgrade(string displayName, int currentLevel) =>
            TryGetByDisplayName(displayName, out var spec) && currentLevel < spec.MaxUpgrades;

        public static int GetXpCostPerLevel(string displayName) =>
            TryGetByDisplayName(displayName, out var spec) ? spec.XpCostPerLevel : 0;

        static Dictionary<string, UpgradeSpec> Build() => new()
        {
            ["基础斩击"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1伤害
            ["举盾格挡"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1护甲
            ["防御架势"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 5, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +5%减伤
            ["战吼鼓舞"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1伤害
            ["先发制人"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1伤害
            ["猛力劈砍"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1伤害
            ["护盾猛击"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1伤害
            ["以退为进"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1护甲
            ["剑柄猛击"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1伤害
            ["嘲讽挑衅"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 2, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +2护甲
            ["荆棘护甲"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1护甲
            ["铁壁弹反"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 5, ReflectPercentPerLevel = 10, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +5%减伤，+10%反弹伤害
            ["刀枪不入"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 2, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +2%减伤
            ["应对姿态"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1护甲
            ["战意觉醒"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 1, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1%增伤
            ["重甲强化"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 3, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // 额外+3%护甲
            ["战士冲锋"] = new() { MaxUpgrades = 5, DamagePerLevel = 3, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +3伤害
            ["报复打击"] = new() { MaxUpgrades = 5, DamagePerLevel = 2, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +2伤害
            ["誓死守护"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 5, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +5%减伤
            ["战斗咆哮"] = new() { MaxUpgrades = 2, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 1, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1%增伤
            ["致命打击"] = new() { MaxUpgrades = 5, DamagePerLevel = 3, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +3伤害
            ["剑刃风暴"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +1伤害
            ["战术大师的终结技"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // 应对次数额外+1（比如升级一次从×5变×6）
            ["借机攻击架势"] = new() { MaxUpgrades = 5, DamagePerLevel = 2, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +2伤害
            ["怒火焚身"] = new() { MaxUpgrades = 3, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // 生命每低5%，伤害额外+1
            ["不屈意志"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 5, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +5恢复HP
            ["无畏冲锋"] = new() { MaxUpgrades = 5, DamagePerLevel = 3, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +3伤害
            ["重整旗鼓"] = new() { MaxUpgrades = 2, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 1, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +1抽牌数
            ["天神下凡"] = new() { MaxUpgrades = 5, DamagePerLevel = 2, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // +2伤害
            ["最终壁垒"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 5, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // -5%清除护甲
            ["沙暴射线"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1伤害
            ["祈祷祝福"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 1, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1HP
            ["沙之箭"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1伤害
            ["沙之盾"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1护甲
            ["圣甲虫护盾"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1护甲
            ["太阳之怒"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1伤害
            ["腐烂之触"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1伤害
            ["沙尘结界"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1护甲
            ["生命汲取"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1伤害
            ["法老权令"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 1, DefenseUpPercentPerLevel = 1, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1伤害，+1护甲
            ["瘟疫蔓延"] = new() { MaxUpgrades = 4, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 5, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +5%传染概率
            ["亡灵诅咒"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 1, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1伤害，+1层中毒
            ["日光审判"] = new() { MaxUpgrades = 5, DamagePerLevel = 4, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +4伤害
            ["复活祝福"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +5%恢复HP
            ["沙矛重塑"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +1伤害
            ["神圣灌注"] = new() { MaxUpgrades = 1, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 1, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // 费用-1
            ["太阳神之怒"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // 额外重复一次
            ["太阳神的庇佑"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +1护甲
            ["腐朽化身"] = new() { MaxUpgrades = 8, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 1, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // +1层中毒
            ["生命之泉"] = new() { MaxUpgrades = 2, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 1, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // +1回复HP
            ["暗影爪击"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1伤害
            ["恶魔诅咒"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 2, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +2%虚弱
            ["恶魔之触"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1伤害
            ["鲜血铠甲"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1护甲
            ["恶魔契约"] = new() { MaxUpgrades = 2, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1伤害
            ["掠血之手"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 2, VulnerablePerLevel = 2, XpCostPerLevel = 10 }, // +1伤害，+2%破损和虚弱
            ["苦痛转化"] = new() { MaxUpgrades = 3, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 1, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1护甲，+1回复HP
            ["鲜血撕咬"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1伤害
            ["黑暗之雾"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 2, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1伤害，+2%虚弱
            ["吸血光环"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +5%回复HP
            ["血尾贯穿"] = new() { MaxUpgrades = 5, DamagePerLevel = 2, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +2伤害
            ["生命虹吸"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1伤害
            ["血焰爆发"] = new() { MaxUpgrades = 5, DamagePerLevel = 2, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +2伤害
            ["黑暗撕裂"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 2, XpCostPerLevel = 15 }, // +2%破损
            ["灵魂撕裂"] = new() { MaxUpgrades = 5, DamagePerLevel = 2, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +2伤害
            ["诅咒之链"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1伤害，目标受到的伤害+1
            ["地狱烈焰"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1伤害
            ["暗黑献祭"] = new() { MaxUpgrades = 5, DamagePerLevel = 4, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +4伤害
            ["鲜血狂欢"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 1, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +1%增伤
            ["血族传承"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 5, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +5%最大HP
            ["魔王降临"] = new() { MaxUpgrades = 5, DamagePerLevel = 4, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +4伤害
            ["魔神回响"] = new() { MaxUpgrades = 5, DamagePerLevel = 5, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // +5伤害
            ["无尽血刃"] = new() { MaxUpgrades = 5, DamagePerLevel = 5, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // +5伤害
            ["分血仪式"] = new() { MaxUpgrades = 4, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 5, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // +5%回复HP
            ["最终鲜血仪式"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 1, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // +1回复HP
            ["蛇牙撕咬"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1伤害
            ["蟒蛇守护"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1护甲
            ["鳞片硬化"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1护甲
            ["剧毒之触"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1伤害
            ["女王威信"] = new() { MaxUpgrades = 1, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 1, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1抽牌数
            ["蛇尾突袭"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1伤害
            ["毒鳞"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 1, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1层中毒
            ["毒液喷吐"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 1, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1层中毒
            ["毒雾弥漫"] = new() { MaxUpgrades = 3, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 1, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1层中毒
            ["蜕皮"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 1, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1回复HP
            ["蛇信感知"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 1, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1层中毒
            ["女王的预防"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 5, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +5%减伤
            ["毒囊破裂"] = new() { MaxUpgrades = 2, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 1, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1层中毒
            ["巨蟒绞杀"] = new() { MaxUpgrades = 5, DamagePerLevel = 5, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +5伤害
            ["不朽蛇蜕"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 2, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +2%增伤
            ["万蛇噬心"] = new() { MaxUpgrades = 6, DamagePerLevel = 5, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // +5伤害
            ["女王之吻"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 3, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // +3层中毒
            ["蛇神的回应"] = new() { MaxUpgrades = 5, DamagePerLevel = 5, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 2, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // +5伤害，+2层中毒
            ["蓄能"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 2, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +2%增伤
            ["灵质护盾"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 1, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1护甲
            ["幽灵爪击"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 8 }, // +1伤害
            ["灵能炮"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1伤害
            ["灵能箭雨"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 10 }, // +1伤害
            ["灵魂风暴"] = new() { MaxUpgrades = 5, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +1伤害
            ["灵魂吞噬"] = new() { MaxUpgrades = 1, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 99, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // 变为0点能量消耗
            ["灵能体"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 2, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +2%增伤
            ["灵魂强化"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 2, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +2%增伤
            ["灵界爆发"] = new() { MaxUpgrades = 5, DamagePerLevel = 2, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +2伤害
            ["灵能聚集"] = new() { MaxUpgrades = 5, DamagePerLevel = 2, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // +2伤害
            ["灵界封印"] = new() { MaxUpgrades = 1, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 1, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 15 }, // 费用-1
            ["灵魂挽歌"] = new() { MaxUpgrades = 2, DamagePerLevel = 1, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +1额外伤害
            ["召唤卡牌之灵"] = new() { MaxUpgrades = 2, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 1, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +1抽牌数
            ["叹息之墙"] = new() { MaxUpgrades = 5, DamagePerLevel = 0, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 2, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +2%减伤
            ["绝望之魂"] = new() { MaxUpgrades = 5, DamagePerLevel = 2, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 20 }, // +2伤害
            ["超级·无敌·灵能·巨炮"] = new() { MaxUpgrades = 5, DamagePerLevel = 10, BlockPerLevel = 0, HealPerLevel = 0, CostReductionPerLevel = 0, PoisonStacksPerLevel = 0, SlowStacksPerLevel = 0, DrawPerLevel = 0, DamageReductionPerLevel = 0, RespondMitigationPerLevel = 0, ReflectPercentPerLevel = 0, AttackUpPercentPerLevel = 0, DefenseUpPercentPerLevel = 0, WeakenPerLevel = 0, VulnerablePerLevel = 0, XpCostPerLevel = 30 }, // +10伤害
        };
    }
}
